apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-app
  labels:
    app: memory-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-app
  template:
    metadata:
      labels:
        app: memory-app
    spec:
      containers:
      - name: memory-optimized
        image: openjdk:11-jre-slim
        command: ["/bin/bash"]
        args: ["-c", "echo 'import java.util.*; public class MemoryOptimized { public static void main(String[] args) { System.out.println(\"Starting optimized application...\"); List<byte[]> managedMemory = new ArrayList<>(); int iteration = 0; while(true) { try { byte[] chunk = new byte[5 * 1024 * 1024]; managedMemory.add(chunk); iteration++; System.out.println(\"Allocated \" + iteration * 5 + \"MB total - Memory usage controlled\"); Thread.sleep(3000); if(iteration >= 8) { System.out.println(\"Clearing memory to prevent OOM...\"); managedMemory.clear(); System.gc(); iteration = 0; Thread.sleep(5000); } } catch(Exception e) { System.err.println(\"Error: \" + e.getMessage()); System.exit(1); } } } }' > MemoryOptimized.java && javac MemoryOptimized.java && java MemoryOptimized"]
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"  # Richiesta realistica
            cpu: "100m"
          limits:
            memory: "512Mi"  # CORRETTA: Limite adeguato per l'applicazione
            cpu: "200m"
        env:
        - name: JAVA_OPTS
          value: "-Xmx400m -XX:+UseG1GC -XX:MaxGCPauseMillis=100"  # Heap ottimizzato
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "ps aux | grep java | grep -v grep"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "ps aux | grep java | grep -v grep"
          initialDelaySeconds: 15
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: memory-app-service
spec:
  selector:
    app: memory-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

