apiVersion: v1
kind: ConfigMap
metadata:
  name: memory-monitoring-script
data:
  monitor.sh: |
    #!/bin/bash
    echo "=== Memory Monitoring Script ==="
    echo "Monitoring pod memory usage..."
    
    while true; do
      echo "--- $(date) ---"
      
      # Controllare lo stato dei pod
      echo "Pod Status:"
      kubectl get pods -l app=memory-app -o wide
      
      # Controllare l'utilizzo delle risorse
      echo -e "\nResource Usage:"
      kubectl top pods -l app=memory-app 2>/dev/null || echo "Metrics server not available"
      
      # Controllare eventi recenti
      echo -e "\nRecent Events:"
      kubectl get events --field-selector involvedObject.name=$(kubectl get pods -l app=memory-app -o jsonpath='{.items[0].metadata.name}') --sort-by='.lastTimestamp' | tail -5
      
      echo -e "\n" "="*50
      sleep 30
    done
---
apiVersion: batch/v1
kind: Job
metadata:
  name: memory-monitor
spec:
  template:
    spec:
      serviceAccountName: memory-monitor-sa
      containers:
      - name: monitor
        image: bitnami/kubectl:1.10.11-ol-7
        command: ["/bin/bash"]
        args: ["/scripts/monitor.sh"]
        volumeMounts:
        - name: monitoring-script
          mountPath: /scripts
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      volumes:
      - name: monitoring-script
        configMap:
          name: memory-monitoring-script
          defaultMode: 0755
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: memory-monitor-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memory-monitor-role
rules:
- apiGroups: [""]
  resources: ["pods", "events"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: memory-monitor-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: memory-monitor-role
subjects:
- kind: ServiceAccount
  name: memory-monitor-sa
  namespace: default

