apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: node:16-alpine
        command: ["/bin/sh"]
        args: ["-c", "echo 'const express = require(\"express\"); const app = express(); if (!process.env.DATABASE_URL) { console.error(\"Error: DATABASE_URL environment variable is required\"); process.exit(1); } app.get(\"/\", (req, res) => res.send(\"Hello World! DB: \" + process.env.DATABASE_URL)); app.listen(3000, () => console.log(\"Server running on port 3000\"));' > /app/server.js && cd /app && npm init -y && npm install express && node server.js"]
        ports:
        - containerPort: 3000
        # PROBLEMA: Manca la variabile d'ambiente DATABASE_URL richiesta
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP